# Generated by Django 5.1.7 on 2025-04-23 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="identifier",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="community",
            name="community_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
