# Generated by Django 5.1.7 on 2025-04-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0003_community_identifier_alter_community_community_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="identifier",
        ),
        migrations.AddField(
            model_name="subrabble",
            name="identifier",
            field=models.TextField(blank=True, null=True),
        ),
    ]
