# Generated by Django 5.1.7 on 2025-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0004_remove_community_identifier_subrabble_identifier"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subrabble",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="subrabble",
            name="identifier",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="subrabble",
            unique_together={("community_id", "identifier")},
        ),
    ]
