# Generated by Django 5.1.7 on 2025-04-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0005_alter_subrabble_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="community_name",
            field=models.TextField(unique=True),
        ),
    ]
