# Generated by Django 5.1.7 on 2025-05-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rabble", "0007_commentlike_postlike_delete_likes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="parent_id",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="commentlike",
            old_name="comment_id",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="commentlike",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="community_id",
            new_name="community",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="conversation_id",
            new_name="conversation",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="subrabble_id",
            new_name="subrabble",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="postlike",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="postlike",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="subrabble",
            old_name="community_id",
            new_name="community",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="post_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="rabble.post",
            ),
            preserve_default=False,
        ),
    ]
